- name: Download nvm install script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/creationix/nvm/v0.39.1/install.sh
    dest: /tmp/nvm_install.sh
    mode: "0777"

- name: Install nvm
  become: no
  ansible.builtin.shell: >
    /tmp/nvm_install.sh

- name: Install node
  become: no
  shell: >
    . ~/.nvm/nvm.sh && nvm install {{ item }}
  loop:
    - 16.19.0
