- name: Install docker prereqs
  ansible.builtin.package:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release


- name: Add docker repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 trusted=yes] https://download.docker.com/linux/ubuntu jammy stable"
    state: present
    update_cache: true

- name: Install neovim
  ansible.builtin.package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin        
    state: latest

- name: Enable service
  ansible.builtin.systemd:
    enabled: yes
    name: docker
    state: started
  become: yes

- name: Ensure docker group exist
  ansible.builtin.group:
    name: "docker"
    state: present

- name: Add to group
  ansible.builtin.user:
    append: yes
    groups: docker
    name: "cjs"
